#!/usr/bin/env bash

COUCHDB_EBS=/couchdb/couchdb/
COUCHDB_USER=root # We only support root right now.
COUCHDB_OPTS=" -r 5  -o /dev/null -e /dev/null"

build_pid () {
    local conf=$1

    local port=`basename $conf`

    port=${port/local-/}
    port=${port/.ini/}

    local pid="/var/run/couch-${port}.pid"    

    echo $pid
}

start_lounge () {
    for file in $(find ${COUCHDB_EBS}etc/couchdb -type f -iname 'local-*.ini'); do

        pid_file=$(build_pid $file)

        init_cmd="${COUCHDB_EBS}bin/couchdb"
        init_cmd="${init_cmd} -a ${file}"
        init_cmd="${init_cmd} -b"
        init_cmd="${init_cmd} -p ${pid_file}"
        init_cmd="${init_cmd} ${COUCHDB_OPTS}"

        $init_cmd
    done
}

stop_lounge () {
    for file in $(find ${COUCHDB_EBS}etc/couchdb -type f -iname 'local-*.ini'); do

        stop_cmd="${COUCHDB_EBS}bin/couchdb"
        stop_cmd="${stop_cmd} -a ${file}"
        stop_cmd="${stop_cmd} -b"
        stop_cmd="${stop_cmd} -p ${pid_file}"
        stop_cmd="${stop_cmd} ${COUCHDB_OPTS}"
        stop_cmd="${stop_cmd} -d"

        $stop_cmd
    done
}

# From CouchDB's init script
parse_script_option_list () {
    # Parse arguments passed to the script and take appropriate action.

    case "$1" in
        start)
            start_lounge
            ;;
        stop)
            stop_lounge
            ;;
        *)
            cat << EOF >&2
Usage: $SCRIPT_NAME {start|stop}
EOF
            exit
            ;;
    esac
}

parse_script_option_list $@
