#!/bin/bash

COUCHDB_EBS=/
COUCHDB_USER=root

start_lounge () {
    for file in $(find ${COUCHDB_EBS}etc/couchdb -type f -iname '*.ini'); do

        init_cmd="sudo su -c'${COUCHDB_EBS}usr/bin/couchdb"
        init_cmd="${init_cmd} -c ${file}"
        init_cmd="${init_cmd} -b -r 5"
        init_cmd="${init_cmd} -p ${pid_file}"
        init_cmd="${init_cmd} -o /dev/null -e /dev/null'"
        init_cmd="${init_cmd} ${COUCHDB_USER}"

        echo $init_cmd;
    done
}

stop_lounge () {
    echo "TBD"
}

# From CouchDB's init script
parse_script_option_list () {
    # Parse arguments passed to the script and take appropriate action.

    case "$1" in
        start)
            start_lounge
            ;;
        stop)
            stop_lounge
            ;;
        *)
            cat << EOF >&2
Usage: $SCRIPT_NAME {start|stop}
EOF
            exit
            ;;
    esac
}

parse_script_option_list $@
