#!/usr/bin/php 
<?php
/**
 * +-----------------------------------------------------------------------+
 * | Copyright (c) 2010, Till Klampaeckel                                  |
 * | All rights reserved.                                                  |
 * |                                                                       |
 * | Redistribution and use in source and binary forms, with or without    |
 * | modification, are permitted provided that the following conditions    |
 * | are met:                                                              |
 * |                                                                       |
 * | o Redistributions of source code must retain the above copyright      |
 * |   notice, this list of conditions and the following disclaimer.       |
 * | o Redistributions in binary form must reproduce the above copyright   |
 * |   notice, this list of conditions and the following disclaimer in the |
 * |   documentation and/or other materials provided with the distribution.|
 * | o The names of the authors may not be used to endorse or promote      |
 * |   products derived from this software without specific prior written  |
 * |   permission.                                                         |
 * |                                                                       |
 * | THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS   |
 * | "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT     |
 * | LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR |
 * | A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT  |
 * | OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, |
 * | SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT      |
 * | LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, |
 * | DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY |
 * | THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT   |
 * | (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE |
 * | OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  |
 * |                                                                       |
 * +-----------------------------------------------------------------------+
 * | Author: Till Klampaeckel <till@php.net>                               |
 * +-----------------------------------------------------------------------+
 *
 * PHP version 5
 *
 * @category Database
 * @package  DB_CouchDB
 * @author   Till Klampaeckel <till@php.net>
 * @license  http://www.opensource.org/licenses/bsd-license.php The BSD License
 * @version  GIT: $Id$
 * @link     http://till.klampaeckel.de/blog/
 */


$username = '';
$password = '';
$server   = 'localhost';
$db_dir   = '/couchdb_db1';

foreach (glob('/couchdb/couchdb/etc/couchdb/local-*') as $file) {
    $port = basename($file);
    $port = str_replace('local-', '', $port);
    $port = str_replace('.ini', '', $port);

    $dbs = findDatabase($db_dir, $port);

    foreach ($dbs as $database) {

        $compact = "http://{$server}:{$port}/{$database}/_compact";

        $req = new HTTP_Request2;
        $req->setUrl($compact)
            ->setMethod(HTTP_Request2::METHOD_POST);

        if (!empty($username)) {
            $req->setAuth($username, $password);
        }

        $resp = $req->send();

        $status = json_decode($resp->getBody());
        var_dump($status);

        unset($req);
    }
}

/**
 * Find the database names for the given shard.
 *
 * @param $db_dir
 * @param $port
 *
 * @return array
 */
function findDatabases($db_dir, $port)
{
    $dbs = array();
    foreach (glob($db_dir . '/' . $port . '/*.couch') as $db) {
        $db = basename($db);
        $db = str_replace('.couch', '', $db);

        $dbs[] = $db;
    }
    return $dbs;
}